For review: Add variable rate slope 1 stablecoin update.
GauntletNetworks/aave-proposals-v3 pull request #2
Opened 2023-11-16 20:12 UTC by reem

Same issue with the Metis portion as #1 

Some pending questions from slack:

- For arbitrum in the pt 1 hackmd, there are updates listed for both USDC and USDC.e, the asset options available are USDC and USDCn, can you confirm these are the intended tokens?
- For base, the hackmd lists `USDC` but the available token is `USDbC`, can you also confirm this is the intended token?

2023-11-17 19:26 UTC, katiebk requested changes
amending my previous comment

all USDC going from 0.035 -> 0.05 EXCEPT:
- v3 Base USDbC 0.04 -> 0.05
- v2 Avalanche USDC 0.04 -> 0.05
- v2 Ethereum USDC 0.04 -> 0.05
- v2 Polygon USDC 0.04 -> 0.05

2023-11-17 19:48 UTC, katiebk commented on diffs/AaveV2Avalanche_IncreaseStablecoinOptimalBorrowRates_20231116_before_AaveV2Avalanche_IncreaseStablecoinOptimalBorrowRates_20231116_after.md
> +| variableRateSlope1 | 4 % | 5 % |
3.5% ->  5%

2023-11-17 19:48 UTC, katiebk commented on diffs/AaveV2Ethereum_IncreaseStablecoinOptimalBorrowRates_20231116_before_AaveV2Ethereum_IncreaseStablecoinOptimalBorrowRates_20231116_after.md
> +| variableRateSlope1 | 4 % | 5 % |
3.5% -> 5%

2023-11-17 19:48 UTC, katiebk commented on diffs/AaveV2Polygon_IncreaseStablecoinOptimalBorrowRates_20231116_before_AaveV2Polygon_IncreaseStablecoinOptimalBorrowRates_20231116_after.md
> +| variableRateSlope1 | 4 % | 5 % |
3.5% -> 5%

2023-11-17 19:48 UTC, katiebk commented on diffs/AaveV3Base_IncreaseStablecoinOptimalBorrowRates_20231116_before_AaveV3Base_IncreaseStablecoinOptimalBorrowRates_20231116_after.md
base isn't included in the hackmd but the snapshot is for all markets. variableslope1=0.04 for USDbC so this is correct

2023-11-17 19:48 UTC, katiebk commented on diffs/AaveV3Metis_IncreaseStablecoinOptimalBorrowRates_20231116_before_AaveV3Metis_IncreaseStablecoinOptimalBorrowRates_20231116_after.md
> +| variableRateSlope1 | 4 % | 5 % |
we don't have interest rate parameters ingested for metis so i can't use bigquery to confirm whether the before value is correct

2023-11-17 20:02 UTC, katiebk approved these changes

2023-11-17 20:19 UTC, katiebk requested changes

2023-11-17 20:19 UTC, katiebk commented on src/20231116_Multi_IncreaseStablecoinOptimalBorrowRates/IncreaseStablecoinOptimalBorrowRates.md
> +| Ethereum v2  | USDC   | variableRateSlope1 | 0.035         | 0.05              |
so this actually needs to be changed then for the hackmd. all v2 USDC current values = 0.04

2023-11-17 20:19 UTC, katiebk commented on src/20231116_Multi_IncreaseStablecoinOptimalBorrowRates/IncreaseStablecoinOptimalBorrowRates.md
> +| Avalanche v2 | USDC   | variableRateSlope1 | 0.035         | 0.05              |
change here

2023-11-17 20:19 UTC, katiebk commented on src/20231116_Multi_IncreaseStablecoinOptimalBorrowRates/IncreaseStablecoinOptimalBorrowRates.md
> +| Polygon v2   | USDC   | variableRateSlope1 | 0.035         | 0.05              |
change here

2023-11-17 20:33 UTC, reem commented
Updated current values in proposal description

2023-11-17 20:48 UTC, katiebk approved these changes

2023-11-18 00:06 UTC, ndelzingaro88 reviewed
Added some comments for the PR

2023-11-18 00:08 UTC, reem commented on diffs/AaveV3Arbitrum_IncreaseStablecoinOptimalBorrowRates_20231116_before_AaveV3Arbitrum_IncreaseStablecoinOptimalBorrowRates_20231116_after.md
> +## Reserve changes
Walter removed MAI, context I think is the MAI deprecation proposal also going up on monday

2023-11-27 22:33 UTC, closed without merging